### ISSUE TITLE
Differences with atom-import-cost

### ISSUE THREAD

**Issue by julien-f** [IanMitchell/import-cost-atom#3]
Hi!

What are the differences with [atom-import-cost](https://github.com/siddharthkp/atom-import-cost)?

Maybe you should join forces :)

**Comment by IanMitchell** [comment]
They're using an API to determine cost, I'm using Wix's module - looks like they didn't want to go through with the additional build step post-package install, which makes sense. If people would rather not do that, atom-import-cost is a great solution - if they're ok with the rebuild, this package works well :)

**Comment by IanMitchell** [comment]
@julien-f mind if I close, or have any other questions? 😃

**Comment by julien-f** [comment]
FYI https://github.com/siddharthkp/atom-import-cost/pull/3

Thanks for your answer :-)
