### ISSUE TITLE
The mport-cost-atom element is repeated

### ISSUE THREAD

**Issue by id77** [IanMitchell/import-cost-atom#4]
I add a mark to watch.
![vnazai0u2h](https://user-images.githubusercontent.com/9592236/29737789-ccbf3534-8a46-11e7-8142-004701da91a3.gif)

repeatedly changes.
![image](https://user-images.githubusercontent.com/9592236/29737795-0af17902-8a47-11e7-9b7b-5524561f4159.png)

They are overlapping together.

Save.
![jpv6wxrqea](https://user-images.githubusercontent.com/9592236/29739803-7c676254-8a79-11e7-9dde-f2b41b7c5b5a.gif)

Click split windows.
![poutkzrn7v](https://user-images.githubusercontent.com/9592236/29739793-406fe3a2-8a79-11e7-9329-71c5e806a656.gif)

**Comment by IanMitchell** [comment]
Interesting, thank you! Will look into this ASAP. Also appreciate the amazing visuals 👍

**Comment by IanMitchell** [comment]
Fixed in 1.0.4 - the split-pane view demonstration made this super easy to find, can't thank you enough for the visualizations!
