### ISSUE TITLE
Uncaught TypeError: Cannot read property 'blockHeight' of undefined

### ISSUE THREAD

**Issue by id77** [IanMitchell/import-cost-atom#5]
[https://github.com/gandm/language-babel/issues/415](https://github.com/gandm/language-babel/issues/415)

Maybe a decorator.

**Comment by IanMitchell** [comment]
How did you trigger this? I haven't seen it before, not sure what could be causing it

**Comment by IanMitchell** [comment]
Oh, I see. Trying to delete a line that's been marked up throws the problem. Yeah this is probably me - looking into it.

**Comment by IanMitchell** [comment]
Pretty stuck on this one. Still working on it

**Comment by id77** [comment]
now it's okay
big tnx 👍

**Comment by IanMitchell** [comment]
Thank @Arcanemagus haha, all him! Glad it's better now 😁
